### ISSUE TITLE
O terceiro teste de TestUpdateCategory: test_cannot_update_category_with_empty_name

### ISSUE THREAD

**Issue by emperormades** [gcrsaldanha/codeflix-catalog-admin#5]
```python
def test_cannot_update_category_with_empty_name(self):
    with pytest.raises(ValueError, match="name cannot be empty"):
        Category(name="")
```

Aqui você está chamando o Category, e deveria chamar o método update-category. Se você tirar o self.validate() de dentro update_category, o teste ainda vai passar desse jeito. 
sugestão:

```python
def test_cannot_update_category_with_empty_name(self):
    name = self.faker.word()
    description = self.faker.sentence()
    updated_name = ""
    updated_description = self.faker.sentence()
    category = Category(name=name, description=description)

    with pytest.raises(ValueError, match="name can't be empty"):
        category.update_category(
            name=updated_name, 
            description=updated_description
        )
```

**Comment by gcrsaldanha** [comment]
Obrigado @madeseladrian ! Corrigi essa issue aqui: https://github.com/gcrsaldanha/codeflix-catalog-admin/pull/8

Gostei da sua utilização do `faker`!

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mehrdad-shokri, @gklo, @Imranok, @haoolii, @Randy808, @schaefbauer, @sdwuyawen, @maolivn, @epsalm, @modood, @svetoslav-mechev, @alantess, @gionatamettifogo, @namastecrypto, @abu271, @tutncrusoe, @geordee, @selimbiber, @kamal3951, @xiaopingz, @yyong1, @ozanbatuhanceylan, @bundarachada, @mperk, @greg-tbca, @vseae, @Gowtham5134, @Diversified1, @kevinalh, @tou55aint, @ecass777, @Caisin, @YunwenL, @FDani3, @Carlesgg97, @Monte9, @cnn007, @thalysmcarrara, @ph0enixd0wn420, @eightrivers, @huyhoangphan29, @zheer100, @freezy63, @stevenshelby, @0xZangetsudev, @Enochyoung, @RRLEAK, @robsoncruzs, @tgsl8r, @Venoox
